name: api_client
description: Marvel API client
version: 0.0.1
environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  di:
  dio:
  get_it:
  injectable:
  json_annotation:
  retrofit:

dev_dependencies:
  analysis:
  build_runner:
  injectable_generator:
  json_serializable:
  retrofit_generator:
