name: api_client_interceptors
description: Interceptors for our api client
version: 0.0.1
environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  api_client:
  di:
  dio:
  flutter:
    sdk: flutter
  get_it:
  injectable:
  mocked_be:
  monitoring:
  platform_info:

dev_dependencies:
  analysis:
  build_runner:
  checks:
  flutter_test:
    sdk: flutter
  injectable_generator:
  mocktail:
