targets:
  $default:
    builders:
      injectable_generator|injectable_config_generator:
        generate_for:
          - lib/src/di/di_initializer.dart
      retrofit_generator|retrofit_generator:
        generate_for:
          - lib/src/domain/api**/*.dart
      freezed|freezed:
        generate_for:
          - lib/src/entrypoint**/*_state.dart
          - lib/src/domain/api/model**/*.dart
          - lib/src/domain/model**/*.dart
          - lib/src/presentation**/*_bloc.dart
          - lib/src/presentation**/model**/*_bloc.dart
      json_serializable:
        generate_for:
          - lib/src/domain/api/model**/*.dart
          - lib/src/domain/model**/*.dart
        options:
          include_if_null: false
          explicit_to_json: true
      bdd_widget_test|featureBuilder:
        options:
          include: package:bdd_steps/bdd_options.yaml
        generate_for:
          - test/feature**/*.feature
      i69|yamlBasedBuilder:
        generate_for:
          - lib/src/presentation**/localization/translations/*.yaml
        options:
          nomap: true
          notraverse: true
global_options:
  freezed:
    runs_before:
      - json_serializable
      - injectable_generator
  json_serializable:
    runs_before:
      - retrofit_generator
