name: questionnaire
description: Flow example implementation
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.5
  flutter: ^3.41.7

resolution: workspace

dependencies:
  di:
  design_system:
  flutter:
    sdk: flutter
  flutter_bloc:
  freezed_annotation:
  get_it:
  retrofit:
  dio:
  api_client:
  injectable:
  prelude:
  entrypoint:
  i69n:
  presenter:
  localizations:
  state_management:

dev_dependencies:
  bdd_steps:
  mocked_be:
  bdd_widget_test:
  mocktail:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  retrofit_generator:
  injectable_generator:
  json_serializable:
  analysis:

flutter:
  uses-material-design: true
