name: flow_builder
description: fork of original flow builder with some modifications
version: 0.0.1

environment:
  sdk: ^3.11.5
  flutter: ^3.41.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  analysis:
  flutter_test:
    sdk: flutter
