name: localizations
description: Package containing common translations and some base localization setup
version: 0.0.1
environment:
  sdk: ^3.11.5
  flutter: ^3.41.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  i69n:

dev_dependencies:
  analysis:
  build_runner:
  checks:
  flutter_test:
    sdk: flutter
