name: navigation
description: Project navigator implementation
version: 0.0.1

environment:
  sdk: ^3.11.5
  flutter: ^3.41.7

resolution: workspace

dependencies:
  auto_route:
  di:
  flutter:
    sdk: flutter
  get_it:
  injectable:
  monitoring:
  questionnaire:
  rick_and_morty_characters:
  sandbox:

dev_dependencies:
  analysis:
  auto_route_generator:
  build_runner:
  injectable_generator:
