name: miniclient
description: Modular app example
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  di:
  get_it:
  injectable:
  entrypoint:
  navigation:
  configuration:
  design_system:
  api_client:
  presenter:
  mocked_be:
  preferences:
  localizations:
  state_management:
  api_client_interceptors:
  monitoring:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  analysis:
  build_runner:
  injectable_generator:

flutter:
  uses-material-design: true
