name: configuration
description: Configuration package to handle app wide access
version: 0.0.1

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  di:
  get_it:
  injectable:
  sandbox:

dev_dependencies:
  build_runner:
  analysis:
  injectable_generator:
