name: PR Verification

on:
  pull_request:
    branches: [ main ]

jobs:
  display-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Hello
        run: |
          echo "--------------------------------------------------"
          echo "ACTION SUCCESSFUL: Test text printed successfully!"
          echo "--------------------------------------------------"
