name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  melos-diff-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        melos-script:
          - "analyze:diff"
          - "validate_dependency:diff"
          - "validate_barrel_file_imports:diff"
          - "metrics:metric_unused_files:diff"
          - "metrics:metric_unused_code:diff"
          - "test:diff"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Environment
        uses: ./.github/actions/melos-setup

      - name: "Check: ${{ matrix.melos-script }}"
        run: melos run ${{ matrix.melos-script }}
